files:
  - source: /src/GZCTF/Resources/Program.resx
    translation: /src/GZCTF/Resources/Program.%locale%.resx
  - source: /src/GZCTF/ClientApp/src/locales/en_US/*.json
    translation: /src/GZCTF/ClientApp/src/locales/%locale_with_underscore%/%original_file_name%
